# Configuration for Label Actions - https://github.com/dessant/label-actions

issues:
  actions:
    incomplete:
      comment: >
        @{issue-author}, the issue does not contain enough information
        to reproduce the bug. Please open a new bug report and fill out
        the issue template with the requested data.
      close: true
    wontfix-automation:
      comment: >
        @{issue-author}, full automation and scripting are outside of scope
        for this project due to their potential for misuse.
        The solver must always be manually started from the extension button.
      close: true
    wontfix-service:
      comment: >
        @{issue-author}, the extension helps solve reCAPTCHA audio challenges.
        Other services and challenge types are not supported
        and are outside of scope for this project.
      close: true
